// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemSalesTickets.Data;

#nullable disable

namespace SystemSalesTickets.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261007175607_Add100Seats")]
    partial class Add100Seats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SystemSalesTickets.Core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCancelled = false,
                            Name = "Concert A",
                            NumberOfSeats = 2500,
                            Price = 20.0
                        });
                });

            modelBuilder.Entity("SystemSalesTickets.Core.Models.EventSeat", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("EventSeats");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            SeatId = 1,
                            IsAvailable = false,
                            Version = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            EventId = 1,
                            SeatId = 2,
                            IsAvailable = true,
                            Version = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SystemSalesTickets.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "SeatId")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            EventName = "Concert A",
                            OrderDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SystemSalesTickets.Core.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Row", "Line")
                        .IsUnique();

                    b.ToTable("Seat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Line = 1,
                            Row = 1,
                            Version = new Guid("00000001-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2,
                            Line = 2,
                            Row = 1,
                            Version = new Guid("00000002-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 3,
                            Line = 3,
                            Row = 1,
                            Version = new Guid("00000003-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 4,
                            Line = 4,
                            Row = 1,
                            Version = new Guid("00000004-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 5,
                            Line = 5,
                            Row = 1,
                            Version = new Guid("00000005-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 6,
                            Line = 6,
                            Row = 1,
                            Version = new Guid("00000006-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 7,
                            Line = 7,
                            Row = 1,
                            Version = new Guid("00000007-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 8,
                            Line = 8,
                            Row = 1,
                            Version = new Guid("00000008-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 9,
                            Line = 9,
                            Row = 1,
                            Version = new Guid("00000009-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 10,
                            Line = 10,
                            Row = 1,
                            Version = new Guid("00000010-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 11,
                            Line = 1,
                            Row = 2,
                            Version = new Guid("00000011-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 12,
                            Line = 2,
                            Row = 2,
                            Version = new Guid("00000012-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 13,
                            Line = 3,
                            Row = 2,
                            Version = new Guid("00000013-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 14,
                            Line = 4,
                            Row = 2,
                            Version = new Guid("00000014-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 15,
                            Line = 5,
                            Row = 2,
                            Version = new Guid("00000015-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 16,
                            Line = 6,
                            Row = 2,
                            Version = new Guid("00000016-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 17,
                            Line = 7,
                            Row = 2,
                            Version = new Guid("00000017-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 18,
                            Line = 8,
                            Row = 2,
                            Version = new Guid("00000018-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 19,
                            Line = 9,
                            Row = 2,
                            Version = new Guid("00000019-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 20,
                            Line = 10,
                            Row = 2,
                            Version = new Guid("00000020-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 21,
                            Line = 1,
                            Row = 3,
                            Version = new Guid("00000021-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 22,
                            Line = 2,
                            Row = 3,
                            Version = new Guid("00000022-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 23,
                            Line = 3,
                            Row = 3,
                            Version = new Guid("00000023-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 24,
                            Line = 4,
                            Row = 3,
                            Version = new Guid("00000024-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 25,
                            Line = 5,
                            Row = 3,
                            Version = new Guid("00000025-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 26,
                            Line = 6,
                            Row = 3,
                            Version = new Guid("00000026-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 27,
                            Line = 7,
                            Row = 3,
                            Version = new Guid("00000027-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 28,
                            Line = 8,
                            Row = 3,
                            Version = new Guid("00000028-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 29,
                            Line = 9,
                            Row = 3,
                            Version = new Guid("00000029-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 30,
                            Line = 10,
                            Row = 3,
                            Version = new Guid("00000030-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 31,
                            Line = 1,
                            Row = 4,
                            Version = new Guid("00000031-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 32,
                            Line = 2,
                            Row = 4,
                            Version = new Guid("00000032-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 33,
                            Line = 3,
                            Row = 4,
                            Version = new Guid("00000033-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 34,
                            Line = 4,
                            Row = 4,
                            Version = new Guid("00000034-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 35,
                            Line = 5,
                            Row = 4,
                            Version = new Guid("00000035-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 36,
                            Line = 6,
                            Row = 4,
                            Version = new Guid("00000036-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 37,
                            Line = 7,
                            Row = 4,
                            Version = new Guid("00000037-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 38,
                            Line = 8,
                            Row = 4,
                            Version = new Guid("00000038-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 39,
                            Line = 9,
                            Row = 4,
                            Version = new Guid("00000039-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 40,
                            Line = 10,
                            Row = 4,
                            Version = new Guid("00000040-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 41,
                            Line = 1,
                            Row = 5,
                            Version = new Guid("00000041-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 42,
                            Line = 2,
                            Row = 5,
                            Version = new Guid("00000042-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 43,
                            Line = 3,
                            Row = 5,
                            Version = new Guid("00000043-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 44,
                            Line = 4,
                            Row = 5,
                            Version = new Guid("00000044-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 45,
                            Line = 5,
                            Row = 5,
                            Version = new Guid("00000045-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 46,
                            Line = 6,
                            Row = 5,
                            Version = new Guid("00000046-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 47,
                            Line = 7,
                            Row = 5,
                            Version = new Guid("00000047-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 48,
                            Line = 8,
                            Row = 5,
                            Version = new Guid("00000048-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 49,
                            Line = 9,
                            Row = 5,
                            Version = new Guid("00000049-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 50,
                            Line = 10,
                            Row = 5,
                            Version = new Guid("00000050-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 51,
                            Line = 1,
                            Row = 6,
                            Version = new Guid("00000051-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 52,
                            Line = 2,
                            Row = 6,
                            Version = new Guid("00000052-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 53,
                            Line = 3,
                            Row = 6,
                            Version = new Guid("00000053-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 54,
                            Line = 4,
                            Row = 6,
                            Version = new Guid("00000054-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 55,
                            Line = 5,
                            Row = 6,
                            Version = new Guid("00000055-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 56,
                            Line = 6,
                            Row = 6,
                            Version = new Guid("00000056-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 57,
                            Line = 7,
                            Row = 6,
                            Version = new Guid("00000057-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 58,
                            Line = 8,
                            Row = 6,
                            Version = new Guid("00000058-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 59,
                            Line = 9,
                            Row = 6,
                            Version = new Guid("00000059-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 60,
                            Line = 10,
                            Row = 6,
                            Version = new Guid("00000060-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 61,
                            Line = 1,
                            Row = 7,
                            Version = new Guid("00000061-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 62,
                            Line = 2,
                            Row = 7,
                            Version = new Guid("00000062-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 63,
                            Line = 3,
                            Row = 7,
                            Version = new Guid("00000063-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 64,
                            Line = 4,
                            Row = 7,
                            Version = new Guid("00000064-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 65,
                            Line = 5,
                            Row = 7,
                            Version = new Guid("00000065-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 66,
                            Line = 6,
                            Row = 7,
                            Version = new Guid("00000066-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 67,
                            Line = 7,
                            Row = 7,
                            Version = new Guid("00000067-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 68,
                            Line = 8,
                            Row = 7,
                            Version = new Guid("00000068-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 69,
                            Line = 9,
                            Row = 7,
                            Version = new Guid("00000069-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 70,
                            Line = 10,
                            Row = 7,
                            Version = new Guid("00000070-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 71,
                            Line = 1,
                            Row = 8,
                            Version = new Guid("00000071-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 72,
                            Line = 2,
                            Row = 8,
                            Version = new Guid("00000072-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 73,
                            Line = 3,
                            Row = 8,
                            Version = new Guid("00000073-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 74,
                            Line = 4,
                            Row = 8,
                            Version = new Guid("00000074-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 75,
                            Line = 5,
                            Row = 8,
                            Version = new Guid("00000075-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 76,
                            Line = 6,
                            Row = 8,
                            Version = new Guid("00000076-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 77,
                            Line = 7,
                            Row = 8,
                            Version = new Guid("00000077-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 78,
                            Line = 8,
                            Row = 8,
                            Version = new Guid("00000078-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 79,
                            Line = 9,
                            Row = 8,
                            Version = new Guid("00000079-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 80,
                            Line = 10,
                            Row = 8,
                            Version = new Guid("00000080-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 81,
                            Line = 1,
                            Row = 9,
                            Version = new Guid("00000081-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 82,
                            Line = 2,
                            Row = 9,
                            Version = new Guid("00000082-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 83,
                            Line = 3,
                            Row = 9,
                            Version = new Guid("00000083-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 84,
                            Line = 4,
                            Row = 9,
                            Version = new Guid("00000084-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 85,
                            Line = 5,
                            Row = 9,
                            Version = new Guid("00000085-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 86,
                            Line = 6,
                            Row = 9,
                            Version = new Guid("00000086-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 87,
                            Line = 7,
                            Row = 9,
                            Version = new Guid("00000087-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 88,
                            Line = 8,
                            Row = 9,
                            Version = new Guid("00000088-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 89,
                            Line = 9,
                            Row = 9,
                            Version = new Guid("00000089-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 90,
                            Line = 10,
                            Row = 9,
                            Version = new Guid("00000090-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 91,
                            Line = 1,
                            Row = 10,
                            Version = new Guid("00000091-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 92,
                            Line = 2,
                            Row = 10,
                            Version = new Guid("00000092-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 93,
                            Line = 3,
                            Row = 10,
                            Version = new Guid("00000093-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 94,
                            Line = 4,
                            Row = 10,
                            Version = new Guid("00000094-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 95,
                            Line = 5,
                            Row = 10,
                            Version = new Guid("00000095-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 96,
                            Line = 6,
                            Row = 10,
                            Version = new Guid("00000096-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 97,
                            Line = 7,
                            Row = 10,
                            Version = new Guid("00000097-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 98,
                            Line = 8,
                            Row = 10,
                            Version = new Guid("00000098-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 99,
                            Line = 9,
                            Row = 10,
                            Version = new Guid("00000099-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 100,
                            Line = 10,
                            Row = 10,
                            Version = new Guid("00000100-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("SystemSalesTickets.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "15000",
                            IsBlocked = false,
                            Password = "AQAAAAIAAYagAAAAEA1k61jf211sNrnVlnardNcGL3S3o4S7xxODit7eCsR8LChzkSZzH1LEABC8M47emg==",
                            Phone = "0556667788",
                            Role = 2,
                            UserName = "Avi"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@example.com",
                            IsBlocked = false,
                            Password = "AQAAAAIAAYagAAAAEEgW8PRhBaBx46pxAz/cboT2Ca/gB+JZ3XxBtqCudaDHMLhbhUNrKRHHtnfoDkHuUA==",
                            Phone = "0556367788",
                            Role = 1,
                            UserName = "Moshe"
                        });
                });

            modelBuilder.Entity("SystemSalesTickets.Core.Models.EventSeat", b =>
                {
                    b.HasOne("SystemSalesTickets.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemSalesTickets.Core.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("SystemSalesTickets.Core.Models.Order", b =>
                {
                    b.HasOne("SystemSalesTickets.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemSalesTickets.Core.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemSalesTickets.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Seat");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
